import { z } from 'zod';
const Profile=z.object({headline:z.string().default(''),summary:z.string().default(''),skills:z.array(z.string()).default([]),experience:z.array(z.object({role:z.string(),company:z.string(),period:z.string(),description:z.string()})).default([]),projects:z.array(z.object({name:z.string(),description:z.string(),url:z.string().optional()})).default([]),education:z.array(z.object({school:z.string(),degree:z.string(),period:z.string()})).default([]),contact:z.object({email:z.string().optional(),location:z.string().optional(),website:z.string().optional(),linkedin:z.string().optional(),github:z.string().optional()}).default({})});
async function callAI(prompt:string){
 const key=process.env.OPENAI_API_KEY||process.env.AI_API_KEY; if(!key) throw new Error('AI provider is not configured. Add OPENAI_API_KEY in Vercel.');
 const r=await fetch('https://api.openai.com/v1/chat/completions',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${key}`},body:JSON.stringify({model:process.env.OPENAI_MODEL||process.env.AI_MODEL||'gpt-4o-mini',messages:[{role:'system',content:'You are a professional career writer. Return valid JSON only. Never invent facts; improve wording only from supplied facts.'},{role:'user',content:prompt}],temperature:.4,response_format:{type:'json_object'}})});
 if(!r.ok) throw new Error(`OpenAI request failed: ${await r.text()}`); const j=await r.json(); return Profile.parse(JSON.parse(j.choices?.[0]?.message?.content||'{}'));
}
export async function generateProfile(input:string,type:'portfolio'|'resume'){return callAI(`Create structured ${type} content from these notes. Preserve facts and omit unknowns.\n\n${input}`)}
export async function rewriteText(text:string,instruction:string){const r=await callAI(`Return JSON {"headline":"","summary":"","skills":[],"experience":[],"projects":[],"education":[],"contact":{}} where summary contains the rewritten text. Instruction: ${instruction}\nText: ${text}`); return r.summary||text;}
